### PR TITLE
Prefer string interpolation to join

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Less is more.

### CODE REVIEW

**Comment by johnbellone** [comment]
@jeffbyrnes Can you rebase?

**Comment by jeffbyrnes** [comment]
Sure thing!

--
Jeff Byrnes
@thejeffbyrnes (https://twitter.com/thejeffbyrnes)
thejeffbyrnes.com (http://thejeffbyrnes.com/)

**Comment by jeffbyrnes** [comment]
@johnbellone all rebased.

**Comment by johnbellone** [comment]
You want to rebase against latest changes you made?

**Comment by jeffbyrnes** [comment]
@johnbellone sure thing! Thanks for collab status, I’ll tackle getting this merged in & a new release cut.

**Pull request merged**
